version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  node:
    build:
      context: ..
      dockerfile: docker/node.Dockerfile
    ports: ["3001:3001"]
    volumes:
      - ../common:/app/common:ro
  python:
    build:
      context: ..
      dockerfile: docker/python.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    ports: ["3002:3002"]
  go:
    build:
      context: ..
      dockerfile: docker/go.Dockerfile
    ports: ["3003:3003"]
  cpp:
    build:
      context: ..
      dockerfile: docker/cpp.Dockerfile
    ports: ["3004:3004"]
  gateway:
    build:
      context: ..
      dockerfile: docker/node.Dockerfile
    command: ["node", "node/dist/src/index.js"]
    ports: ["8080:8080"]
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on: [redis, node, python]


